### PR TITLE
add documentation of unisex name

### PR DESCRIPTION
**Pull request by BruceUBC**

### CODE REVIEW

**Review by DanielCairns — APPROVED** [review]
Good for Milestone 1.

**Comment by DanielCairns** [comment]
I think we should decide whether our functions return a list or return just a single name for consistency.

**Comment by DanielCairns** [comment]
Also, remember we have the data already so in practice it might not be an input to the function. Same goes for your "limit" - we probably want default values for both

**Comment by BruceUBC** [comment]
OK, sure. I can modify my function after we complete all the functions together.

**Pull request merged**
